apiVersion: batch/v1
kind: Job
metadata:
  name: wordcount-job
spec:
  completions: 2
  parallelism: 2
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: wordcount
          image: wordcount:latest
